version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://rm-2zevy2ft59syyah55ro.mysql.rds.aliyuncs.com:3306/schoolmalldemodb
      SPRING_DATASOURCE_USERNAME: taoduoduo
      SPRING_DATASOURCE_PASSWORD: TaoDuoDuo123

