version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/schoolmalldemodb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: LDQ930446lyx
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: LDQ930446lyx
      MYSQL_DATABASE: schoolmalldemodb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
