apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: 'true'
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-2zeas45cm88tybxu2bj0x
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-ip-version: ipv4
  creationTimestamp: '2024-08-28T03:48:18Z'
  finalizers:
    - service.k8s.alibaba/resources
  labels:
    service.beta.kubernetes.io/hash: 3a6625f24ea38d4853232d313291eade64b7493837479f474976ba41
    service.k8s.alibaba/loadbalancer-id: lb-2zeas45cm88tybxu2bj0x
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type': {}
            'f:service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners': {}
            'f:service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id': {}
            'f:service.beta.kubernetes.io/alibaba-cloud-loadbalancer-ip-version': {}
        'f:spec':
          'f:allocateLoadBalancerNodePorts': {}
          'f:externalTrafficPolicy': {}
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":80,"protocol":"TCP"}':
              .: {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
      manager: ACK-Console Apache-HttpClient
      operation: Update
      time: '2024-08-28T03:48:18Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"service.k8s.alibaba/resources"': {}
      manager: cloud-controller-manager
      operation: Update
      time: '2024-08-28T03:48:18Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:service.beta.kubernetes.io/hash': {}
            'f:service.k8s.alibaba/loadbalancer-id': {}
        'f:status':
          'f:loadBalancer':
            'f:ingress': {}
      manager: cloud-controller-manager
      operation: Update
      subresource: status
      time: '2024-08-28T03:48:24Z'
  name: schoolmall-service
  namespace: default
  resourceVersion: '562636'
  uid: ce6b3aad-6215-45fa-864f-6a08b0e105d6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.181.73
  clusterIPs:
    - 10.0.181.73
  externalTrafficPolicy: Local
  healthCheckNodePort: 32039
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32641
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: schoolmall
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 8.141.22.2
        ipMode: VIP